repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: f8d8c45220230434bd7440d85a7f64c67bcdb952
      hooks:
          - id: trailing-whitespace
          - id: end-of-file-fixer
          - id: check-toml
          - id: check-yaml
          - id: check-added-large-files

    - repo: local
      hooks:
        - id: format
          name: format
          description: Format files with cargo make fmt.
          entry: cargo make format
          language: system
          types: [rust]
          pass_filenames: false
        - id: lint
          name: lint
          description: Lint files with cargo make lint.
          entry: cargo make lint
          language: system
          types: [rust]
          pass_filenames: false
        - id: check
          name: check
          description: Check files with Cargo Check
          entry: cargo check
          language: system
          types: [rust]
          pass_filenames: false
