repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: f8d8c45220230434bd7440d85a7f64c67bcdb952
      hooks:
          - id: trailing-whitespace
          - id: end-of-file-fixer
          - id: check-toml
          - id: check-yaml
          - id: check-added-large-files

    - repo: https://github.com/doublify/pre-commit-rust
      rev: v1.0
      hooks:
          - id: fmt
          - id: cargo-check
          - id: clippy
