name: Deploy Updated Global Commands

on:
  push:
    branches: 
      - main
    paths:
      - 'chuckle-interactions/commands.lock.json'
      - '.github/workflows/commands.yml'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: chortle

    steps:
      - name: Checkout Commands Lockfile
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            chuckle-interactions/commands.lock.json
          sparse-checkout-cone-mode: false

      - name: PUT Global Commands
        run: |
          curl -X PUT https://discord.com/api/v10/applications/${{ secrets.DISCORD_APPLICATION_ID }}/commands \
            -H "Authorization: Bot ${{ secrets.DISCORD_TOKEN }}" \
            -H "content-type: application/json" \
            -d @./chuckle-interactions/commands.lock.json | jq
