name: Database Migrations

on:
  push:
    branches:
      - main
    paths:
      - 'migrations/**'
  workflow_dispatch:

jobs:
  gcr:
    name: Apply Database Migrations
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: cargo-${{ runner.os }}-${{ hashFiles('**/Cargo.lock') }}

      - uses: r7kamura/rust-problem-matchers@v1

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install sqlx-cli
        run: cargo install sqlx-cli@0.7.1 --no-default-features --features native-tls,postgres

      - name: Connect to Cloud SQL
        uses: ahmadnassri/action-google-cloud-sql-proxy@v1
        with:
          key: ${{ secrets.CLOUD_SQL_JSON_KEY }}
          connection: ${{ secrets.CLOUD_SQL_CONNECTION }}
          port: 5432

      - name: Apply Migrations
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: sqlx migrate run
