name: CI

env:
  SQLX_OFFLINE: true
  CARGO_TERM_COLOR: always

on:
  push:
    branches:
      - main
    paths-ignore:
      - "**.md"
  pull_request:
    paths-ignore:
      - "**.md"

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  check:
    name: Test Suite
    runs-on: chortle
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Problem Matchers
        uses: r7kamura/rust-problem-matchers@v1

      - run: rustup toolchain install stable --profile minimal

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install Cargo Make
        uses: davidB/rust-cargo-make@v1

      - name: Run Formatter
        run: cargo make format-ci

      - name: Run Clippy
        run: cargo make lint-ci

      - name: Build
        run: cargo check --all-features
