name: Tests

env:
  SQLX_OFFLINE: true

on:
  push:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  check:
    name: Lint, Format, and Build
    runs-on: chortle
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cache Cargo
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: cargo-${{ runner.os }}-${{ hashFiles('**/Cargo.lock') }}

      - name: Setup Problem Matchers
        uses: r7kamura/rust-problem-matchers@v1

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Run Formatter
        run: cargo fmt --all --check

      - name: Run Clippy
        run: cargo clippy -- -D warnings

      - name: Build
        run: cargo build --all-features --release
